export default {
  card: ['itemNo', 'name', 'styleUrl', 'salePrice', 'type'],
  collage: [
    'id',
    'name',
    'backgroundUrl',
    'thumbnail',
    'minPeople',
    'priceRange',
    'salePrice',
    'labelPrice',
    'virCount',
    'itemNo',
    'actualCount',
  ],
  coupons: [
    'id',
    'name',
    'discountFee',
    'minimumFee',
    'couponBackgroundStyle',
    'couponBackgroundUrl',
    'couponType',
    'fixedTerm',
    'beginTime',
    'endTime',
    'receiveMethod',
    'integral',
    'quantity',
    'issueAmount',
    'couponCategory',
  ],
  goods: [
    'itemNo',
    'name',
    'subName',
    'thumbnail',
    'salePrice',
    'labelPrice',
    'virtualSalesVolume',
    'salesType',
    'displayPrice',
    'mode',
    'integralPrice',
  ],
  haggle: [
    'id',
    'itemNo',
    'itemName',
    'activityName',
    'thumbnail',
    'salePrice',
    'lowestPrice',
    'virtualPeople',
    'assistCount',
    'bargainTimes',
    'skuId',
  ],
  freeGoods: [
    'id',
    'itemNo',
    'name',
    'thumbnail',
    'attrValCombineName',
    'levelName',
    'virtualPeople',
    'everyoneLimitCount',
    'receivedCount',
  ],
  giftCard: ['id', 'name', 'bgImg'],
  activity: ['thumbnail', 'salePrice', 'labelPrice', 'name', 'itemNo'],
  preSale: ['itemNo'],
  article: ['id', 'title', 'viewsCount', 'updateTime', 'coverUrl'], // 营销图文
  seckill: [
    'id',
    'name',
    'itemNo',
    'thumbnail',
    'salePrice',
    'priceRange',
    'peopleLimitAmount',
    'salesVolume',
    'status',
  ],
  cardPack: ['id', 'name', 'salePrice', 'itemImageUrls', 'subtitle', 'buyLimit', 'cardSalesVolume'],
  microDecorate: ['id', 'name', 'appointmentNum', 'approvalNum', 'thumbnail', 'vrUrl', 'viewNum'],
  ebooks: ['id', 'coverUrl', 'title', 'albumStatus', 'pdfUrl', 'updateTime', 'categoryName'], // 电子画册
  integral: ['id', 'itemThumbnail', 'paidNum', 'itemList', 'itemName'], // 积分
  promotion: ['id', 'name', 'ruleName'],
  equityGoods: ['mid', 'name', 'icon', 'pointCost', 'count', 'value', 'link'],
  scoreTask: ['mid', 'name', 'icon', 'pointCost', 'count', 'value', 'link'],
  scoreActivity: ['activityId', 'title', 'icon', 'link'],
  merchant: [
    'id',
    'name',
    'logo',
    'avgConsume',
    'buildingName',
    'floor',
    'mallStoreCode',
    'subtitle',
    'tenantCategoryName',
  ],
};
