// 零售行业的组件配置
function getComponents(opt) {
  const { ableLivePlay } = opt || { ableLivePlay: false };
  const components = [];
  const componentsList = [
    {
      type: '基础组件',
      components: [
        {
          id: 'posterModule',
          name: '海报',
          config: {
            margin: 0,
            radius: 0,
            marginUp: 5,
            marginDown: 5,
            marginLeftRight: 0,
            data: [],
            exampleData: [],
            isLock: false,
          },
        },
        {
          id: 'imageModule',
          name: '轮播图',
          config: {
            margin: 0,
            radius: 0,
            marginUp: 5,
            marginDown: 5,
            marginLeftRight: 0,
            height: 240,
            data: [],
            exampleData: [],
            isLock: false,
          },
        },
        {
          id: 'titleModule',
          name: '标题',
          config: {
            componentsPadding: 10,
            radius: 0,
            marginUp: 5,
            marginDown: 5,
            marginLeftRight: 0,
            margin: 5,
            textAlign: 'left',
            title: '标题',
            backgroundColor: '#FFFFFF',
            titleColor: 'rgba(55,58,68,1)',
            bgMode: 'default', // 背景颜色的选择方式
            titleMode: 'default', // 文字颜色的选择方式
            isLock: false,
          },
        },
        {
          id: 'productModule',
          name: '商品',
          config: {
            componentsPadding: 0,
            radius: 0,
            marginUp: 5,
            marginDown: 5,
            marginLeftRight: 0,
            type: 'product',
            data: [],
            exampleData: [],
            showNav: true,
            // showRectType: 1,
            display: 'vertical',
            textNavSource: {
              componentsPadding: 10,
              fontSize: '16px',
              title: '人气热销',
              subTitle: '更多',
              titleColor: 'rgba(55,58,68,1)',
              subTitleColor: 'rgba(162,162,164,1)',
              linkPage: 'pages/more/index?type=1',
              linkName: '更多商品',
              showMore: '1',
            },
            backgroundColor: 'rgba(246,249,251,1)',
            bgMode: 'default', // 背景颜色的选择方式
            isLock: false,
          },
        },
        {
          id: 'giftCardModule',
          name: '礼品卡',
          config: {
            componentsPadding: 15,
            radius: 0,
            marginUp: 5,
            marginDown: 5,
            marginLeftRight: 0,
            data: [],
            exampleData: [],
            showNav: true,
            textNavSource: {
              componentsPadding: 15,
              fontSize: '16px',
              title: '精选礼品卡',
              subTitle: '礼品卡商城',
              titleColor: 'rgba(55,58,68,1)',
              subTitleColor: 'rgba(162,162,164,1)',
              linkPage: 'pages/gift-card/bg-list/index',
              linkName: '礼品卡商城',
              showMore: '1',
            },
            isLock: false,
          },
        },
        {
          id: 'magicModule',
          name: '魔方',
          config: {
            componentsPadding: 10,
            name: '1row3',
            margin: 10,
            radius: 0,
            marginUp: 5,
            marginDown: 5,
            marginLeftRight: 10,
            data: [
              {
                width: '33.33%',
                height: '100%',
                top: '0%',
                left: '0%',
                src: '',
                linkPage: '',
                linkName: '',
              },
              {
                width: '33.33%',
                height: '100%',
                top: '0%',
                left: '33.33%',
                src: '',
                linkPage: '',
                linkName: '',
              },
              {
                width: '33.33%',
                height: '100%',
                top: '0%',
                left: '66.66%',
                src: '',
                linkPage: '',
                linkName: '',
              },
            ],
            exampleData: [
              {
                width: '33.33%',
                height: '100%',
                top: '0%',
                left: '0%',
                src: '',
                linkPage: '',
                linkName: '',
              },
              {
                width: '33.33%',
                height: '100%',
                top: '0%',
                left: '33.33%',
                src: '',
                linkPage: '',
                linkName: '',
              },
              {
                width: '33.33%',
                height: '100%',
                top: '0%',
                left: '66.66%',
                src: '',
                linkPage: '',
                linkName: '',
              },
            ],
            isLock: false,
          },
        },
        {
          id: 'textNavModule',
          name: '文本导航',
          config: {
            componentsPadding: 10,
            radius: 0,
            marginUp: 5,
            marginDown: 5,
            marginLeftRight: 0,
            fontSize: '16px',
            title: '标题名称',
            subTitle: '更多',
            titleColor: 'rgba(55,58,68,1)',
            subTitleColor: 'rgba(162,162,164,1)',
            bgColor: '#FFFFFF',
            linkPage: '',
            linkName: '',
            showMore: '1',
            bgMode: 'default', // 背景颜色的选择方式
            textMode: 'default', // 文字颜色的选择方式
            isLock: false,
          },
        },
        {
          id: 'navigationModule',
          name: '导航图标',
          config: {
            rowNum: 4,
            circularCorner: 0,
            marginUp: 10,
            marginDown: 0,
            marginLeftRight: 0,
            radius: 0,
            list: [],
            backgroundColor: 'rgba(255,255,255,1)',
            bgMode: 'default', // 背景颜色的选择方式
            titleColor: 'rgba(51, 51, 51, 1)',
            titleMode: 'default', // 文字颜色的选择方式
            isLock: false,
          },
        },
        {
          id: 'topMenuModule',
          name: '顶部菜单',
          config: {
            componentsPadding: 10,
            bgColor: 'rgba(255,187,59,1)',
            titleColor: 'rgba(255, 255, 255, 1)',
            colorModel: 'default',
            alignType: 'left',
            data: [
              {
                title: '推荐',
                linkType: '',
                linkPage: '',
                linkName: '',
              },
              {
                title: '推荐1',
                linkType: '',
                linkPage: '',
                linkName: '',
              },
              {
                title: '推荐2',
                linkType: '',
                linkPage: '',
                linkName: '',
              },
            ],
            isLock: false,
          },
        },
        // {
        //   id: 'activityModule',
        //   name: '专题活动',
        //   config: {
        //     componentsPadding: 10,
        //     data: [],
        //     exampleData: [],
        //     showPoster: true,
        //     display: 'vertical',
        //     limitNum: 4,
        //     marginUp: 5,
        //     marginDown: 5,
        //     marginLeftRight: 10,
        //     radius: 8,
        //     isComponent: true,
        //     isLock: false,
        //   },
        // },
        {
          id: 'hotAreaModule',
          name: '场景购',
          config: {
            data: [],
            src: '',
            width: 0,
            height: 0,
            marginUp: 5,
            marginDown: 5,
            marginLeftRight: 0,
            radius: 0,
            isComponent: true,
            EditAreaMaxWidth: 325,
            isLock: false,
          },
        },
        {
          id: 'scanModule',
          name: '扫码购',
          config: {
            margin: 0,
            radius: 0,
            marginUp: 5,
            marginDown: 5,
            marginLeftRight: 0,
            bgMode: 'default',
            bgUrl: '',
            isLock: false,
          },
        },
        // {
        //   id: 'shopCardModule',
        //   name: '导购名片',
        //   config: {
        //     margin: 0,
        //     radius: 0,
        //     showTips: 0,
        //     marginUp: 5,
        //     marginDown: 5,
        //     marginLeftRight: 0,
        //     data: [],
        //     exampleData: [],
        //     shopGuide: 1,
        //     shopGuideList: [],
        //     cardStyle: 3,
        //     showRules: 1,
        //     isLock: false,
        //   },
        // },
        {
          id: 'videoModule',
          name: '视频',
          config: {
            margin: 0,
            radius: 0,
            marginUp: 5,
            marginDown: 5,
            marginLeftRight: 0,
            data: null,
            exampleData: [],
            isLock: false,
          },
        },
      ],
    },
    {
      type: '营销组件',
      components: [
        {
          id: 'collageModule',
          name: '拼团',
          config: {
            componentsPadding: 10,
            radius: 0,
            marginUp: 5,
            marginDown: 5,
            marginLeftRight: 0,
            data: [],
            showType: 1,
            exampleData: [],
            showNav: true,
            textNavSource: {
              componentsPadding: 10,
              fontSize: '16px',
              title: '精选拼团',
              subTitle: '更多',
              titleColor: 'rgba(55,58,68,1)',
              subTitleColor: 'rgba(162,162,164,1)',
              icon: 'collage-retail-icon',
              linkPage: 'pages/group/list/index',
              linkName: '更多拼团',
              showMore: '1',
            },
            isLock: false,
          },
        },
        {
          id: 'couponsModule',
          name: '优惠券',
          config: {
            type: 'retail',
            componentsPadding: 10,
            radius: 0,
            marginUp: 5,
            marginDown: 5,
            marginLeftRight: 0,
            data: [],
            exampleData: [],
            showNav: true,
            textNavSource: {
              componentsPadding: 10,
              fontSize: '16px',
              title: '必抢神券',
              subTitle: '更多',
              titleColor: 'rgba(55,58,68,1)',
              subTitleColor: 'rgba(162,162,164,1)',
              icon: 'coupons-icon',
              linkPage: 'pages/mine/coupon/index',
              linkName: '领券中心',
              showMore: '1',
            },
            isLock: false,
          },
        },
        {
          id: 'haggleModule',
          name: '砍价',
          config: {
            componentsPadding: 10,
            radius: 0,
            marginUp: 5,
            marginDown: 5,
            marginLeftRight: 0,
            showNav: true,
            data: [],
            exampleData: [],
            showType: 1,
            textNavSource: {
              componentsPadding: 10,
              fontSize: '16px',
              title: '热门砍价',
              subTitle: '好友都在砍',
              titleColor: 'rgba(55,58,68,1)',
              subTitleColor: 'rgba(162,162,164,1)',
              icon: 'haggle-icon',
              linkPage: 'pages/cut-price/list/index',
              linkName: '更多砍价',
              showMore: '1',
            },
            isLock: false,
          },
        },
        {
          id: 'articleModule',
          name: '营销图文',
          config: {
            componentsPadding: 10,
            radius: 0,
            marginUp: 5,
            marginDown: 5,
            marginLeftRight: 0,
            showNav: true,
            data: [],
            exampleData: [],
            textNavSource: {
              componentsPadding: 10,
              fontSize: '16px',
              title: '营销图文',
              categroy: '',
              subTitle: '更多',
              titleColor: 'rgba(55,58,68,1)',
              subTitleColor: 'rgba(162,162,164,1)',
              icon: 'haggle-icon',
              linkPage: 'pages/graph/list/index',
              linkName: '更多图文',
              showMore: '1',
              linkUseKeys: ['title', 'categroy'],
            },
            isLock: false,
          },
        },
        {
          id: 'luckyModule',
          name: '幸运转盘',
          config: {
            data: {
              id: '',
              name: '',
            },
            componentsPadding: 10,
            marginUp: 5,
            marginDown: 5,
            marginLeftRight: 10,
            radius: 8,
            isLock: false,
          },
        },
        {
          id: 'seckillModule',
          name: '秒杀',
          config: {
            componentsPadding: 15,
            radius: 0,
            marginUp: 5,
            marginDown: 5,
            marginLeftRight: 0,
            data: [],
            exampleData: [],
            showNav: true,
            showType: 1,
            textNavSource: {
              componentsPadding: 15,
              fontSize: '16px',
              title: '精选秒杀',
              subTitle: '更多',
              titleColor: 'rgba(55,58,68,1)',
              subTitleColor: 'rgba(162,162,164,1)',
              linkPage: 'sub-packages/marketing-package/pages/seckill/list/index',
              linkName: '更多秒杀',
              showMore: '1',
            },
            isLock: false,
          },
        },
        // {
        //   id: 'integralModule',
        //   name: '积分商城',
        //   config: {
        //     componentsPadding: 10,
        //     radius: 0,
        //     marginUp: 5,
        //     marginDown: 5,
        //     marginLeftRight: 0,
        //     data: [],
        //     showType: 0,
        //     exampleData: [],
        //     showNav: true,
        //     textNavSource: {
        //       componentsPadding: 10,
        //       fontSize: '16px',
        //       title: '积分商城',
        //       subTitle: '更多',
        //       titleColor: 'rgba(55,58,68,1)',
        //       subTitleColor: 'rgba(162,162,164,1)',
        //       icon: 'collage-retail-icon',
        //       linkPage: 'pages/mine/integral-mall/index',
        //       linkName: '更多',
        //       showMore: '1',
        //     },
        //     isLock: false,
        //   },
        // },
        {
          id: 'freeModule',
          name: '赠品',
          config: {
            componentsPadding: 10,
            radius: 0,
            marginUp: 5,
            marginDown: 5,
            marginLeftRight: 0,
            data: [],
            exampleData: [],
            showNav: true,
            showType: 1,
            textNavSource: {
              componentsPadding: 10,
              fontSize: '16px',
              title: '赠品专区',
              subTitle: '更多',
              titleColor: 'rgba(55,58,68,1)',
              subTitleColor: 'rgba(162,162,164,1)',
              linkPage: 'wxat-common/pages/mine/free-center/index',
              linkName: '更多赠品',
              showMore: '1',
            },
            backgroundColor: 'rgba(246,249,251,1)',
            bgMode: 'default', // 背景颜色的选择方式
            isLock: false,
          },
        },
        // {
        //   id: 'cardPackModule',
        //   name: '代金卡包',
        //   config: {
        //     componentsPadding: 10,
        //     radius: 0,
        //     marginUp: 5,
        //     marginDown: 5,
        //     marginLeftRight: 0,
        //     data: [],
        //     exampleData: [],
        //     showNav: true,
        //     showType: 1,
        //     textNavSource: {
        //       componentsPadding: 10,
        //       fontSize: '16px',
        //       title: '卡包专区',
        //       subTitle: '更多',
        //       titleColor: 'rgba(55,58,68,1)',
        //       subTitleColor: 'rgba(162,162,164,1)',
        //       linkPage: 'sub-packages/marketing-package/pages/card-pack/list/index',
        //       linkName: '更多卡包',
        //       showMore: '1',
        //     },
        //     backgroundColor: 'rgba(246,249,251,1)',
        //     bgMode: 'default', // 背景颜色的选择方式
        //     isLock: false,
        //   },
        // },
        // {
        //   id: 'promotionModule',
        //   name: '促销活动',
        //   config: {
        //     componentsPadding: 10,
        //     data: [],
        //     exampleData: [],
        //     goodsData: [],
        //     showPoster: true,
        //     posterData: [],
        //     textNavSource: {
        //       title: '促销活动',
        //       subTitle: '更多',
        //       showMore: '1',
        //       titleColor: 'rgba(55,58,68,1)',
        //       fontSize: '16px',
        //     },
        //     display: 'vertical',
        //     limitNum: 4,
        //     marginUp: 5,
        //     marginDown: 5,
        //     marginLeftRight: 10,
        //     radius: 8,
        //     isComponent: true,
        //     isLock: false,
        //   },
        // },
        // {
        //   id: 'equityGoodsModule',
        //   name: '权益商品',
        //   config: {
        //     componentsPadding: 15,
        //     radius: 8,
        //     marginUp: 8,
        //     marginDown: 8,
        //     marginLeftRight: 8,
        //     data: [],
        //     exampleData: [],
        //     showNav: true,
        //     display: 'vertical',
        //     backgroundColor: 'rgba(246,249,251,1)',
        //     bgMode: 'default', // 背景颜色的选择方式
        //     textNavSource: {
        //       componentsPadding: 15,
        //       fontSize: '16px',
        //       title: '热门第三方权益',
        //       subTitle: '更多',
        //       titleColor: 'rgba(55,58,68,1)',
        //       subTitleColor: 'rgba(162,162,164,1)',
        //       linkPage: 'sub-packages/marketing-package/pages/shanhu/equityGood/index',
        //       linkName: '更多',
        //       showMore: '1',
        //     },
        //     isLock: false,
        //   },
        // },
        // {
        //   id: 'scoreActivityModule',
        //   name: '积分活动',
        //   config: {
        //     componentsPadding: 15,
        //     radius: 8,
        //     marginUp: 8,
        //     marginDown: 8,
        //     marginLeftRight: 8,
        //     data: [],
        //     exampleData: [],
        //     showNav: true,
        //     showType: 1,
        //     textNavSource: {
        //       componentsPadding: 15,
        //       fontSize: '16px',
        //       title: '积分活动',
        //       subTitle: '更多',
        //       titleColor: 'rgba(55,58,68,1)',
        //       subTitleColor: 'rgba(162,162,164,1)',
        //       linkPage: 'sub-packages/marketing-package/pages/shanhu/scoreActivity/index',
        //       linkName: '更多',
        //       showMore: '1',
        //     },
        //     isLock: false,
        //   },
        // },
        // {
        //   id: 'scoreTaskModule',
        //   name: '积分任务',
        //   config: {
        //     componentsPadding: 15,
        //     radius: 8,
        //     marginUp: 8,
        //     marginDown: 8,
        //     marginLeftRight: 8,
        //     data: [],
        //     exampleData: [],
        //     showNav: true,
        //     showType: 1,
        //     textNavSource: {
        //       componentsPadding: 15,
        //       fontSize: '16px',
        //       title: '积分任务',
        //       subTitle: '更多',
        //       titleColor: 'rgba(55,58,68,1)',
        //       subTitleColor: 'rgba(162,162,164,1)',
        //       linkPage: 'sub-packages/marketing-package/pages/shanhu/scoreTask/index',
        //       linkName: '更多',
        //       showMore: '1',
        //     },
        //     isLock: false,
        //   },
        // },
      ],
    },
    {
      type: '其他组件',
      components: [
        // {
        //   id: 'storeModule',
        //   name: '店铺信息',
        //   config: {
        //     componentsPadding: 10,
        //     logo: '',
        //     radius: 0,
        //     marginUp: 5,
        //     marginDown: 5,
        //     marginLeftRight: 0,
        //     isLock: false,
        //   },
        // },
        {
          id: 'assistBlankModule',
          name: '辅助空白',
          config: {
            height: 30,
            backgroundColor: null,
            bgMode: 'default',
            defaultColor: '#FFFFFF',
            isLock: false,
          },
        },
        {
          id: 'assistLineModule',
          name: '辅助线',
          config: {
            style: 'dashed',
            lineColor: '#878181',
            showMargin: 'false',
            lineMode: 'default',
            isLock: false,
          },
        },
      ],
    },
  ];

  // 内测组件
  const insideComponents = {
    type: 'vip组件',
    components: [
      {
        id: 'posterRecommendModule',
        name: '猜你喜欢',
        config: {
          posterTitle: '猜你喜欢',
          posterUrl: '',
          wkPosterUrl: '',
          showPoster: true,
          display: 'vertical',
          limitNum: 4,
          marginUp: 5,
          marginDown: 5,
          marginLeftRight: 10,
          radius: 8,
          isLock: false,
        },
      },
    ],
  };

  // 直播组件（需权限）
  const liveAuthComponents = {
    type: '定制组件',
    components: [
      {
        id: 'liveModule',
        name: '直播',
        config: {
          margin: 0,
          radius: 0,
          marginUp: 5,
          marginDown: 5,
          marginLeftRight: 0,
          data: {
            src: process.env.VUE_APP_CDN_URL + '/resources/dss-web-portal/cdn/live/live-default-bg-tiny.png',
            roomId: '',
          },
          isLock: false,
        },
      },
    ],
  };

  componentsList.forEach(item => {
    components.push(item);
  });

  // 判断当前应用程序特征是否为百佳，如果是则添加内测组件
  // components.push(insideComponents);

  if (ableLivePlay) {
    components.push(liveAuthComponents);
  }
  return components;
}

module.exports = {
  components: getComponents,
};
