import goodsTypeEnum from '@/dss-wechat3rd/src/constants/goodsTypeEnum.js';

export default {
  page: {
    HOME_PAGE: 'wxat-common/pages/home/index',
    CLASSIFY_PAGE: 'wxat-common/pages/classify/index',
    SHOPPING_CART_PAGE: 'wxat-common/pages/tabbar-shopping-cart/index',
    MINE_PAGE: 'wxat-common/pages/mine/index',
    QUICK_BUY_PAGE: 'wxat-common/pages/quick-buy/index',
    MORE_GROUP_PAGE: 'wxat-common/pages/group/list/index',
    GROUP_DETAIL_PAGE: 'sub-packages/marketing-package/pages/group/detail/index',
    SEC_KILL_DETAIL_PAGE: '/sub-packages/marketing-package/pages/seckill/detail/index',
    CUT_PRICE_DETAIL_PAGE: 'sub-packages/marketing-package/pages/cut-price/detail/index',
    MORE_CUT_PRICE_PAGE: 'wxat-common/pages/cut-price/list/index',
    MORE_GOODS_PAGE: 'wxat-common/pages/more/index?type=1',
    MORE_ESTATE_PAGE: 'wxat-common/pages/more/index?type=32',
    MORE_SERVER_PAGE: 'wxat-common/pages/more/index?type=0',
    MORE_CARD_PAGE: 'wxat-common/pages/more/index?type=4',
    COUPON_CENTER_PAGE: 'wxat-common/pages/mine/coupon/index',
    MORE_GIFT_CARD_PAGE: 'wxat-common/pages/gift-card/bg-list/index',
    ARTICLE_PAGE: 'wxat-common/pages/graph/list/index',
    SEC_KILL_PAGE: 'sub-packages/marketing-package/pages/seckill/list/index',
    MORE_INTEGRAL: 'wxat-common/pages/mine/integral-mall/index',
    FREE_CENTER: 'wxat-common/pages/mine/free-center/index',
    CARD_PACK: 'sub-packages/marketing-package/pages/card-pack/list/index',
    MICRO_DECORATE: 'sub-packages/marketing-package/pages/micro-decorate/list/index',
    ELECTRONIC_BOOKS: 'sub-packages/marketing-package/pages/ebooks/index',
    EQUITYGOODS: 'sub-packages/marketing-package/pages/shanhu/equityGood/index',
    SCORETASK: 'sub-packages/marketing-package/pages/shanhu/scoreActivity/index',
    SCOREACTIVITY: 'sub-packages/marketing-package/pages/shanhu/scoreTask/index',
  },

  // 餐饮
  catering: {
    globalLink: [
      // {
      //   value: 'member-code',
      //   label: '会员码',
      //   index: 'wxat-common/pages/mine/member-code/index',
      //   linkType: 0,
      // },
      {
        value: 'recharge-center',
        label: '充值中心',
        index: 'wxat-common/pages/mine/recharge-center/index',
        linkType: 0,
        tips: '充值',
      },
      {
        value: 'gift-card-mall',
        label: '礼品卡商城',
        index: 'wxat-common/pages/gift-card/bg-list/index',
        linkType: 0,
      },
      {
        value: 'coupon-center',
        label: '领券中心',
        index: 'wxat-common/pages/mine/coupon/index',
        linkType: 0,
      },
      {
        value: 'group',
        label: '拼团',
        children: [
          {
            value: 'group-list',
            label: '拼团列表',
            index: 'wxat-common/pages/group/list/index',
            linkType: 0,
          },
          {
            value: 'group-detail',
            label: '拼团详情',
            index: 'wxat-common/pages/group/detail/index?itemNo=',
            linkType: 1,
            linkId: 'group',
            tips: '拼团',
          },
        ],
      },
      {
        value: 'cut-price',
        label: '砍价',
        children: [
          {
            value: 'cut-price-list',
            label: '砍价列表',
            index: 'wxat-common/pages/cut-price/list/index',
            linkType: 0,
          },
          {
            value: 'cut-price-detail',
            label: '砍价详情',
            index: 'wxat-common/pages/cut-price/detail/index?activityId=',
            linkType: 1,
            linkId: 'haggle',
            tips: '砍价',
          },
        ],
      },
      {
        value: 'seckill',
        label: '秒杀',
        children: [
          {
            value: 'seckill-list',
            label: '秒杀列表',
            index: 'sub-packages/marketing-package/pages/seckill/list/index',
            linkType: 0,
          },
          {
            value: 'seckill-detail',
            label: '秒杀详情',
            index: 'sub-packages/marketing-package/pages/seckill/detail/index?itemNo=',
            linkType: 1,
            linkId: 'seckill',
            tips: '秒杀',
          },
        ],
      },
      {
        value: 'product',
        label: '商品',
        children: [
          {
            value: 'product-list',
            label: '商品列表',
            index: 'wxat-common/pages/more/index?type=1',
            linkType: 0,
          },
          {
            value: 'product-category',
            label: '商品分类',
            index: 'wxat-common/pages/category-detail/index?id=',
            linkType: 1,
            linkId: 'category',
            tips: '分类',
          },
          {
            value: 'product-detail',
            label: '商品详情',
            index: 'wxat-common/pages/goods-detail/index?itemNo=',
            linkType: 1,
            linkId: 'product',
            tips: '商品',
          },
        ],
      },
      {
        value: 'graph',
        label: '图文',
        children: [
          {
            value: 'graph-list',
            label: '图文列表',
            index: 'wxat-common/pages/graph/list/index',
            linkType: 0,
          },
          {
            value: 'graph-category',
            label: '图文分类',
            index: 'wxat-common/pages/graph/list/index',
            linkType: 1,
            linkId: 'articleClassify',
            tips: '分类',
          },
          {
            value: 'graph-detail',
            label: '图文详情',
            index: 'wxat-common/pages/graph/detail/index?id=',
            linkType: 1,
            linkId: 'article',
            tips: '图文',
          },
        ],
      },
      {
        value: 'gift',
        label: '赠品',
        children: [
          {
            value: 'gift-center',
            label: '赠品中心',
            index: 'wxat-common/pages/mine/free-center/index',
            linkType: 0,
          },
          {
            value: 'gift-detail',
            label: '赠品详情',
            index: 'wxat-common/pages/goods-detail/index?activityId=',
            linkType: 1,
            linkId: 'gift',
            tips: '赠品',
          },
        ],
      },
      // {
      //   value: 'card-pack',
      //   label: '代金卡包',
      //   children: [
      //     {
      //       value: 'card-pack-center',
      //       label: '卡包列表',
      //       index: 'sub-packages/marketing-package/pages/card-pack/list/index',
      //       linkType: 0,
      //     },
      //     {
      //       value: 'card-pack-detail',
      //       label: '卡包详情',
      //       index: 'sub-packages/marketing-package/pages/card-pack/detail/index?id=',
      //       linkType: 1,
      //       linkId: 'card-pack',
      //       tips: '卡包',
      //     },
      //   ],
      // },
      {
        value: 'lucky-dial',
        label: '幸运转盘',
        index: 'wxat-common/pages/lucky-dial/index?id=',
        linkType: 1,
        linkId: 'luckyDial',
        tips: '活动',
      },
      // {
      //   value: 'activity',
      //   label: '专题活动',
      //   index: 'sub-packages/marketing-package/pages/activity/index?topicId=',
      //   linkType: 1,
      //   linkId: 'activity',
      //   tips: '专题',
      // },
      // {
      //   value: 'integral',
      //   label: '积分商城',
      //   index: 'wxat-common/pages/mine/integral-mall/index',
      //   linkType: 0,
      //   linkId: 'integral',
      //   tips: '积分',
      // },
      // {
      //   value: 'nearby-store',
      //   label: '附近门店',
      //   index: 'wxat-common/pages/store-list/index',
      //   linkType: 0,
      // },
      // {
      //   value: 'internal-purchase',
      //   label: '内购专区',
      //   index: 'sub-packages/distribution-package/pages/internal-purchase/center/index',
      //   linkType: 0,
      // },
      // {
      //   value: 'form-tool',
      //   label: '问卷',
      //   index: 'sub-packages/marketing-package/pages/form-tool/index?formId=',
      //   linkType: 1,
      //   linkId: 'formTool',
      //   tips: '问卷',
      // },
      // {
      //   value: 'task-center',
      //   label: '品牌代言人',
      //   index: 'sub-packages/marketing-package/pages/task-center/index',
      //   linkType: 0,
      // },
      // {
      //   value: 'promotion',
      //   label: '促销活动',
      //   index: 'sub-packages/marketing-package/pages/promotion/index?activityId=',
      //   linkType: 1,
      //   linkId: 'promotion',
      //   tips: '活动',
      // },
      {
        value: 'live-list',
        label: '直播列表',
        index: 'sub-packages/live-package/pages/live-list/index',
        linkType: 0,
      },
      // {
      //   value: 'coral-url',
      //   label: '腾讯珊瑚Url',
      //   index: 'coral-url',
      //   linkName: '小程序跳转',
      //   linkType: 0,
      //   tip: '链接',
      // },
      // {
      //   value: '24haowan-url',
      //   label: '游戏Url',
      //   index: '24haowan-url',
      //   linkName: '小程序跳转',
      //   linkType: 0,
      //   tip: '链接',
      // },
      // {
      //   value: 'scoreActivity',
      //   label: '珊瑚积分活动',
      //   linkType: 1,
      //   children: [
      //     {
      //       value: 'scoreActivity-detail',
      //       label: '积分活动',
      //       index: 'wxat-common/pages/webview/index',
      //       linkType: 1,
      //       linkId: 'scoreActivity',
      //       tips: '活动',
      //     },
      //   ],
      // },
    ],
  },
};
