const prefix = process.env.VUE_APP_CDN_URL + '/resources/dss-web-portal/cdn/wxma/';

export default {
  mine: {
    mine_black_bg: prefix + 'mine/black-bg.png',
    mine_kangyang_bg: prefix + 'mine/kangyang-bg.png',
    vipCardBg: prefix + 'mine/vip-card-bg.png',
    unsignVipCardBg: prefix + 'mine/unsign-vip-card-bg.png',
    vipIcon: prefix + 'mine/vip-icon.png',
    defaultAvatar: prefix + 'mine/default-avatar.png',
    waitPay: prefix + 'mine/ic-wait-pay.png',
    waitShipping: prefix + 'mine/ic-wait-shipping.png',
    waitReceive: prefix + 'mine/ic-wait-receive.png',
    afterSale: prefix + 'mine/ic-after-sale.png',
    allOrder: prefix + 'mine/ic-all-order.png',
    cutPrice: prefix + 'mine/ic-cut-price.png',
    group: prefix + 'mine/ic-group.png',
    redPacket: prefix + 'mine/ic-red-packet.png',
    coupon: prefix + 'mine/ic-coupon.png',
    integral: prefix + 'mine/ic-integral.png',
    giftCard: prefix + 'mine/ic-gift-card.png',
    bindMember: prefix + 'mine/ic-bind-member.png',
    addressManage: prefix + 'mine/ic-address-manage.png',
    health: prefix + 'mine/ic-health.png',
    preBuy: prefix + 'mine/ic-pre-buy.png',
    distribution: prefix + 'mine/ic-distribution.png',
    appointment: prefix + 'mine/ic-appointment.png',
    cart: prefix + 'mine/ic-cart.png',
    hotelOrder: prefix + 'mine/ic-hotel-order.png',
    integralLucky: prefix + 'mine/ic-integral-lucky.png',
    memberCode: prefix + 'mine/ic-member-code.png',
    settings: prefix + 'mine/ic-settings.png',
    signin: prefix + 'mine/ic-signin.png',
    ticketOrder: prefix + 'mine/ic-ticket-order.png',
    cardTicket: prefix + 'mine/ic-card-ticket.png',
    gift: prefix + 'mine/ic-gift.png',
    internal: prefix + 'mine/ic-internal.png',
    taskCenter: prefix + 'mine/ic-task-center.png',
    cardPack: prefix + 'mine/ic-card-pack.png',
    myReservation: prefix + 'mine/ic-my-reservation.png',
    promotionAmbassador: prefix + 'mine/ic-promotion-ambassador.png',
    drug: prefix + 'mine/ic-drug.png',
    verification: prefix + 'mine/verification.png',
    scoreDetail: prefix + 'mine/score-detail.png',
    growthDetail: prefix + 'mine/growth-detail.png',
    memberRights: prefix + 'mine/member-rights.png',
    share: prefix + 'mine/share.png',
    entityGift: prefix + 'mine/ic-entity-gift.png',
    parking: prefix + 'mine/ic-parking.png',
    nofeeling: prefix + 'mine/ic-nofeeling.png',
    exchangeMoney: prefix + 'mine/ic-exchangeMoney.png',
  },
  decorate: {
    modulePlh: prefix + 'decorate/icon-plh.png',
  },
};
