import cdnResConfig from '@/business-common/utils/cdnResConfig.js';

export default [
  // {
  //   name: '会员码',
  //   value: 'MEMBER_CODE',
  //   defaultLogo: cdnResConfig.mine.memberCode,
  //   logo: cdnResConfig.mine.memberCode,
  //   checked: true,
  // },
  {
    name: '我的砍价',
    value: 'MINE_CUT_PRICE',
    defaultLogo: cdnResConfig.mine.cutPrice,
    logo: cdnResConfig.mine.cutPrice,
    checked: true,
  },
  {
    name: '我的拼团',
    value: 'MINE_GROUP',
    defaultLogo: cdnResConfig.mine.group,
    logo: cdnResConfig.mine.group,
    checked: true,
  },
  {
    name: '我的红包',
    value: 'MINE_RED_PACKET',
    defaultLogo: cdnResConfig.mine.redPacket,
    logo: cdnResConfig.mine.redPacket,
    checked: true,
  },
  {
    name: '购物车',
    value: 'CART',
    defaultLogo: cdnResConfig.mine.cart,
    logo: cdnResConfig.mine.cart,
    checked: true,
  },
  {
    name: '领券中心',
    value: 'COUPON_CENTER',
    defaultLogo: cdnResConfig.mine.coupon,
    logo: cdnResConfig.mine.coupon,
    checked: true,
  },
  // {
  //   name: '积分商城',
  //   value: 'INTEGRAL_MALL',
  //   defaultLogo: cdnResConfig.mine.integral,
  //   logo: cdnResConfig.mine.integral,
  //   checked: true,
  // },
  {
    name: '礼品卡商城',
    value: 'GIFT_CARD_LIST',
    defaultLogo: cdnResConfig.mine.giftCard,
    logo: cdnResConfig.mine.giftCard,
    checked: true,
  },
  // {
  //   name: '签到',
  //   value: 'SIGN_IN',
  //   defaultLogo: cdnResConfig.mine.signin,
  //   logo: cdnResConfig.mine.signin,
  //   checked: true,
  // },
  {
    name: '赠品专区',
    value: 'FREE_CENTER',
    defaultLogo: cdnResConfig.mine.gift,
    logo: cdnResConfig.mine.gift,
    checked: true,
  },
  // {
  //   name: '内购专区',
  //   value: 'INTERNAL_PURCHASE',
  //   defaultLogo: cdnResConfig.mine.internal,
  //   logo: cdnResConfig.mine.internal,
  //   checked: true,
  // },
  /* {
    name: '幸运抽奖',
    value: 'LUCKY_LIST',
    defaultLogo: cdnResConfig.mine.integralLucky,
    logo: cdnResConfig.mine.integralLucky,
    checked: true
  }, */
  {
    name: '地址管理',
    value: 'ADDRESS_MANAGE',
    defaultLogo: cdnResConfig.mine.addressManage,
    logo: cdnResConfig.mine.addressManage,
    checked: true,
  },
  {
    name: '个人信息',
    value: 'MINE_CENTER',
    defaultLogo: cdnResConfig.mine.settings,
    logo: cdnResConfig.mine.settings,
    checked: true,
  },
  {
    name: '分销中心',
    value: 'DISTRIBUTION',
    defaultLogo: cdnResConfig.mine.distribution,
    logo: cdnResConfig.mine.distribution,
    checked: true,
  },
  // {
  //   name: '品牌代言人',
  //   value: 'TASK_CENTER',
  //   defaultLogo: cdnResConfig.mine.taskCenter,
  //   logo: cdnResConfig.mine.taskCenter,
  //   checked: true,
  // },
  // {
  //   name: '店员核销',
  //   value: 'VERIFICATION',
  //   defaultLogo: cdnResConfig.mine.verification,
  //   logo: cdnResConfig.mine.verification,
  //   checked: true,
  // },
  // {
  //   name: '积分明细',
  //   value: 'SCORE_DETAIL',
  //   defaultLogo: cdnResConfig.mine.scoreDetail,
  //   logo: cdnResConfig.mine.scoreDetail,
  //   checked: true,
  // },
  // {
  //   name: '成长值明细',
  //   value: 'GROWTH_DETAIL',
  //   defaultLogo: cdnResConfig.mine.growthDetail,
  //   logo: cdnResConfig.mine.growthDetail,
  //   checked: true,
  // },
  // {
  //   name: '会员权益',
  //   value: 'MEMBER_RIGHTS',
  //   defaultLogo: cdnResConfig.mine.memberRights,
  //   logo: cdnResConfig.mine.memberRights,
  //   checked: true,
  // },
  // {
  //   name: '我是团长',
  //   value: 'COMMNUNITY_GROUP_BUY',
  //   defaultLogo: cdnResConfig.mine.group,
  //   logo: cdnResConfig.mine.group,
  //   checked: true,
  // },
  // {
  //   name: '我的活动',
  //   value: 'MYACTIVITY',
  //   defaultLogo: cdnResConfig.mine.myReservation,
  //   logo: cdnResConfig.mine.myReservation,
  //   checked: true,
  // },
  // {
  //   name: '我的礼品',
  //   value: 'MY_ENTITY_GIFT',
  //   defaultLogo: cdnResConfig.mine.entityGift,
  //   logo: cdnResConfig.mine.entityGift,
  //   checked: true,
  // },
];
